// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.0
// 	 protoc        v3.20.1
// source: google/api/index.ts

import * as api from "./_export";
export { api };
