// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.0
// 	 protoc        v3.20.1
// source: cosmos/bank/v1beta1/_export.ts

export * from "./bank";
export * from "./tx";
