// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.0
// 	 protoc        v3.20.1
// source: tendermint/libs/index.ts

import * as libs from "./_export";
export { libs };
