name: Build

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: arduino/setup-protoc@v1
      - run: ./submodule-init.sh
      - run: git submodule update --force
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test

