name: Release

on:
  push:
    tags:
      - "v*"
jobs:
  main:
    name: Publish Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      #     registry-url: <registry url>
      # - uses: arduino/setup-protoc@v1
      # - run: ./submodule-init.sh
      # - run: git submodule update
      # - run: yarn install --frozen-lockfile
      # - run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}