// Code generated by protoc-gen-as. DO NOT EDIT.
// versions:
// 	 protoc-gen-as v0.3.0-alpha.0
// 	 protoc        v3.20.1
// source: tendermint/p2p/index.ts

import * as p2p from "./_export";
export { p2p };
